#pragma once

enum CODEC_ID
{
	CODEC_ID_UNKNOWN = 0,
	CODEC_ID_V_MPEG1 = 1,
	CODEC_ID_V_MPEG2,
	CODEC_ID_V_MPEG4,
	CODEC_ID_V_MPEG4_AVC = 0x10,
	CODEC_ID_V_MPEGH_HEVC,
	CODEC_ID_V_VC1 = 0x100,
	CODEC_ID_V_WMV,
	CODEC_ID_V_VP8 = 0x200,
	CODEC_ID_V_VP9,
	CODEC_ID_V_AV1,

	CODEC_ID_A_LPCM_BIG_ENDIAN = 0x80000000,
	CODEC_ID_A_LPCM_LITTLE_ENDIAN,
	CODEC_ID_A_LPCM_BLURAY,
	CODEC_ID_A_LPCM_FLOAT,

	CODEC_ID_A_AC3 = 0x80001000,
	CODEC_ID_A_DOLBY_DIGITAL_PLUS,
	CODEC_ID_A_DOLBY_TRUEHD,

	CODEC_ID_A_DTS = 0x80002000,
	CODEC_ID_A_DTSHD,
	CODEC_ID_A_DTSHD_XLL,

	CODEC_ID_A_MPEG_L3 = 0x80003000,
	CODEC_ID_A_MPEG_L2,
	CODEC_ID_A_MPEG_L1,
	CODEC_ID_A_MPEG2_AAC,
	CODEC_ID_A_MPEG4_AAC,

	CODEC_ID_A_VORBIS = 0x8000F000,
	CODEC_ID_A_FLAC,
};