/*

MIT License

Copyright (c) 2021 Ravin.Wang(wangf1978@hotmail.com)

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

*/
#include "platcomm.h"
#include "nal_com.h"

const char* itu_t_t35_country_code_names[256] = {
	"Japan",
	"Albania",
	"Algeria",
	"American Samoa",
	"Germany(Federal Republic of)",
	"Anguilla",
	"Antigua and Barbuda",
	"Argentina",
	"Ascension(see S.Helena)",
	"Australia",
	"Austria",
	"Bahamas",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Belgium",
	"Belize",
	"Benin(Republic of)",
	"Bermudas",
	"Bhutan(Kingdom of)",
	"Bolivia",
	"Botswana",
	"Brazil",
	"British Antarctic Territory",
	"British Indian Ocean Territory",
	"British Virgin Islands",
	"Brunei Darussalam",
	"Bulgaria",
	"Myanmar(Union of)",
	"Burundi",
	"Byelorussia",
	"Cameroon",
	"Canada",	/*32*/
	"Cape Verde",
	"Cayman Islands",
	"Central African Republic",
	"Chad",
	"Chile",
	"China",
	"Colombia",
	"Comoros",
	"Congo",
	"Cook Islands",
	"Costa Rica",
	"Cuba",
	"Cyprus",
	"Czech and Slovak Federal Republic",
	"Cambodia",
	"Democratic People's Republic of Korea",	/*48*/
	"Denmark",
	"Djibouti",
	"Dominican Republic",
	"Dominica",
	"Ecuador",
	"Egypt",
	"El Salvador",
	"Equatorial Guinea",
	"Ethiopia",
	"Falkland Islands",
	"Fiji",
	"Finland",
	"France",
	"French Polynesia",
	"French Southern and Antarctic Lands",
	"Gabon",	/*64*/
	"Gambia",
	"Germany(Federal Republic of)",
	"Angola",
	"Ghana",
	"Gibraltar",
	"Greece",
	"Grenada",
	"Guam",
	"Guatemala",
	"Guernsey",
	"Guinea",
	"Guinea - Bissau",
	"Guayana",
	"Haiti",
	"Honduras",
	"Hongkong",	/*80*/
	"Hungary(Republic of)",
	"Iceland",
	"India",
	"Indonesia",
	"Iran(Islamic Republic of)",
	"Iraq",
	"Ireland",
	"Israel",
	"Italy",
	"Cote d'Ivoire",
	"Jamaica",
	"Afghanistan",
	"Jersey",
	"Jordan",
	"Kenya",
	"Kiribati",	/*96*/
	"Korea(Republic of)",
	"Kuwait",
	"Lao(People's Democratic Republic)",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Liechtenstein",
	"Luxembourg",
	"Macau",
	"Madagascar",
	"Malaysia",
	"Malawi",
	"Maldives",
	"Mali",
	"Malta",	/*112*/
	"Mauritania",
	"Mauritius",
	"Mexico",
	"Monaco",
	"Mongolia",
	"Montserrat",
	"Morocco",
	"Mozambique",
	"Nauru",
	"Nepal",
	"Netherlands",
	"Netherlands Antilles",
	"New Caledonia",
	"New Zealand",
	"Nicaragua",
	"Niger",	/*128*/
	"Nigeria",
	"Norway",
	"Oman",
	"Pakistan",
	"Panama",
	"Papua New Guinea",
	"Paraguay",
	"Peru",
	"Philippines",
	"Poland(Republic of)",
	"Portugal",
	"Puerto Rico",
	"Qatar",
	"Romania",
	"Rwanda",
	"Saint Kitts and Nevis",	/*144*/
	"Saint Croix",
	"Saint Helena and Ascension",
	"Saint Lucia",
	"San Marino",
	"Saint Thomas",
	"Sao Tomé and Principe",
	"Saint Vincent and the Grenadines",
	"Saudi Arabia",
	"Senegal",
	"Seychelles",
	"Sierra Leone",
	"Singapore",
	"Solomon Islands",
	"Somalia",
	"South Africa",
	"Spain",	/*160*/
	"Sri Lanka",
	"Sudan",
	"Suriname",
	"Swaziland",
	"Sweden",
	"Switzerland",
	"Syria",
	"Tanzania",
	"Thailand",
	"Togo",
	"Tonga",
	"Trinidad and Tobago",
	"Tunisia",
	"Turkey",
	"Turks and Caicos Islands",
	"Tuvalu",	/*176*/
	"Uganda",
	"Ukraine",
	"United Arab Emirates",
	"United Kingdom",
	"United States",
	"Burkina Faso",
	"Uruguay",
	"U.S.S.R.",
	"Vanuatu",
	"Vatican City State",
	"Venezuela",
	"Viet Nam",
	"Wallis and Futuna",
	"Western Samoa",
	"Yemen(Republic of)",
	"Yemen(Republic of)",	/*192*/
	"Yugoslavia",
	"Zaire",
	"Zambia",
	"Zimbabwe",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Escape code to Annex B table",
};

const char* cc_type_names[4] = {
	"NTSC line 21 field 1 closed captions",
	"NTSC line 21 field 2 closed captions",
	"DTVCC Channel Packet Data",
	"DTVCC Channel Packet Start"
};

const char* pic_struct_names[16] = {
	/* 0*/"(progressive)frame",
	/* 1*/"top field",
	/* 2*/"bottom field",
	/* 3*/"top field, bottom field, in that order",
	/* 4*/"bottom field, top field, in that order",
	/* 5*/"top field, bottom field, top field repeated, in that order",
	/* 6*/"bottom field, top field, bottom field repeated, in that order",
	/* 7*/"frame doubling",
	/* 8*/"frame tripling",
	/* 9*/"Top field paired with previous bottom field in output order",
	/*10*/"Bottom field paired with previous top field in output order",
	/*11*/"Top field paired with next bottom field in output order",
	/*12*/"Bottom field paired with next top field in output order",
	/*13*/"reserved"
	/*14*/"reserved",
	/*15*/"reserved",
};

namespace BST
{
	bool more_rbsp_data(AMBst in_bst)
	{
		try
		{
			return AMBst_PeekBits(in_bst, 1) == 1 ? false : true;
		}
		catch (...)
		{
			return false;
		}
	}

}

