name: MacOS_Build

on:
  push:
    branches: [ master ]
    paths:
      - 'src'
      - 'build/common'
      - 'build/macos'
  pull_request:
    branches: [ master ]
    paths:
      - 'src'
      - 'build/common'
      - 'build/macos'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: cd ./build/macos; make
